name: insolar-on-push
# on: [push]
on:
  pull_request:
env:
  GO_VERSION: 1.12.15
  CI_GOMAXPROCS: 0
  INSOLAR_LOG_LEVEL: warn
  GOPATH: /home/admin/actions-runner/_work/insolar/insolar/go
jobs:
  test-func:
    runs-on: self-hosted
    name: test-func
    steps:
      - name: checkout code
        uses: actions/checkout@v1
        with:
          path: go/src/github.com/insolar/insolar
      - name: set up go ${{env.GO_VERSION}}
        uses: actions/setup-go@v1
        with:
          go-version: ${{env.GO_VERSION}}
      - name: add bin to path
        run: echo "::add-path::${{env.GOPATH}}/bin"
      - name: test_unit
        run: |
          make test
        working-directory: ${{env.GOPATH}}/src/github.com/insolar/insolar
      - name: test_slow
        run: |
          make test_slow
        working-directory: ${{env.GOPATH}}/src/github.com/insolar/insolar
      - name: test_func
        run: |
          make functest
        working-directory: ${{env.GOPATH}}/src/github.com/insolar/insolar
