name: pull_request_slow
on:
  pull_request:
env:
  GO_VERSION: 1.12.15
  CI_GOMAXPROCS: 0
  INSOLAR_LOG_LEVEL: warn
  GOPATH: /home/admin/actions-runner/_work/insolar/insolar/go
jobs:
  test-slow:
    runs-on: self-hosted
    name: test-slow
    steps:
      - name: checkout code
        uses: actions/checkout@master
        with:
          path: go/src/github.com/insolar/insolar
      - name: set up go ${{env.GO_VERSION}}
        uses: actions/setup-go@v1
        with:
          go-version: ${{env.GO_VERSION}}
      - name: add bin to path
        run: echo "::add-path::${{env.GOPATH}}/bin"
      - name: test_slow
        run: |
          make build
          make slowtest
        working-directory: ${{env.GOPATH}}/src/github.com/insolar/insolar
