name: run-tests
on:
  pull_request:
env:
  GO_VERSION: 1.12.15
  CI_GOMAXPROCS: 0
  INSOLAR_LOG_LEVEL: warn
  GOPATH: /home/admin/actions-runner/_work/insolar/go
jobs:
  run-all-tests:
    name: GitHub Actions Tests
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@master
        with:
          path: go/src/github.com/insolar/insolar
      - name: set up go ${{env.GO_VERSION}}
        uses: actions/setup-go@v1
        with:
          go-version: ${{env.GO_VERSION}}
      - name: add bin to path
        run: echo "::add-path::${{env.GOPATH}}/bin"
      - name: test_unit
        working-directory: ${{env.GOPATH}}/src/github.com/insolar/insolar
        run: |
          make test
      - name: test_slow_postgresql
        working-directory: ${{env.GOPATH}}/src/github.com/insolar/insolar
        run: |
          make test_slow
      - name: test_slow_cockroachdb
        working-directory: ${{env.GOPATH}}/src/github.com/insolar/insolar
        run: |
          USE_COCKROACH_DB=1 make test_slow
      - name: test_func
        working-directory: ${{env.GOPATH}}/src/github.com/insolar/insolar
        run: |
          make functest
